# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Redacted < Formula
  desc "Claude Code hook that redacts secrets from Bash tool output"
  homepage "https://github.com/svn-arv/redacted"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/svn-arv/redacted/releases/download/v0.2.0/redacted_darwin_amd64.tar.gz"
      sha256 "bdab7c6de2066b370c047792a02404b808fde1d77f64bb324d6d1c59fb504c3d"

      define_method(:install) do
        bin.install "redacted"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/svn-arv/redacted/releases/download/v0.2.0/redacted_darwin_arm64.tar.gz"
      sha256 "99433e007fa419b9488f4367592ee9738d0ad941ed53a8effae21cc982df5292"

      define_method(:install) do
        bin.install "redacted"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/svn-arv/redacted/releases/download/v0.2.0/redacted_linux_amd64.tar.gz"
      sha256 "45923957087dfe34482d0dd992b2a0135a937f85de090b4fd70ba700a152d63b"
      define_method(:install) do
        bin.install "redacted"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/svn-arv/redacted/releases/download/v0.2.0/redacted_linux_arm64.tar.gz"
      sha256 "bbbb4dca2a6f63eb03128c406acda5ec5674b18785653213c30cf2cfd18749cd"
      define_method(:install) do
        bin.install "redacted"
      end
    end
  end

  test do
    system "#{bin}/redacted", "--help"
  end
end
